In [ ]:
import glob
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
import numpy as np
import cv2

In [ ]:
Downdog = glob.glob('/content/drive/MyDrive/DATASET1/DATASET/Downdog/*.*')
Goddness = glob.glob('/content/drive/MyDrive/DATASET1/DATASET/Goddess/*.*')
Plank = glob.glob('/content/drive/MyDrive/DATASET1/DATASET/Plank/*.*')
Tree = glob.glob('/content/drive/MyDrive/DATASET1/DATASET/Tree/*.*')
Warrior = glob.glob('/content/drive/MyDrive/DATASET1/DATASET/Warrior/*.*')

data = []
labels = []

for i in Downdog:   
    image=tf.keras.preprocessing.image.load_img(i, color_mode='rgb', 
    target_size= (200,200))
    image=np.array(image)
    data.append(image)
    labels.append(0)
for i in Goddness:   
    image=tf.keras.preprocessing.image.load_img(i, color_mode='rgb', 
    target_size= (200,200))
    image=np.array(image)
    data.append(image)
    labels.append(1)
for i in Plank:   
    image=tf.keras.preprocessing.image.load_img(i, color_mode='rgb', 
    target_size= (200,200))
    image=np.array(image)
    data.append(image)
    labels.append(2)
for i in Tree:   
    image=tf.keras.preprocessing.image.load_img(i, color_mode='rgb', 
    target_size= (200,200))
    image=np.array(image)
    data.append(image)
    labels.append(3)
for i in Warrior:   
    image=tf.keras.preprocessing.image.load_img(i, color_mode='rgb', 
    target_size= (200,200))
    image=np.array(image)
    data.append(image)
    labels.append(4)

data = np.array(data)
labels = np.array(labels)

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(data, labels, test_size=0.2,
                                                random_state=42)

In [ ]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((288, 200, 200, 3), (73, 200, 200, 3), (288,), (73,))

In [ ]:
x_train = x_train/255.0
x_test = x_test/255.0

In [ ]:
nsamples, nx, ny, nrgb = x_train.shape
x_train1 = x_train.reshape((nsamples,nx*ny*nrgb))

In [ ]:
nsamples, nx, ny, nrgb = x_test.shape
x_test1 = x_test.reshape((nsamples,nx*ny*nrgb))

In [ ]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(random_state=5)
model.fit(x_train1,y_train)

RandomForestClassifier(random_state=5)

In [ ]:
y_pred=model.predict(x_test1)
y_pred

array([1, 0, 0, 4, 0, 2, 4, 4, 2, 4, 3, 3, 3, 0, 2, 2, 3, 2, 1, 1, 0, 2,
       0, 3, 2, 2, 2, 2, 2, 4, 0, 1, 0, 4, 1, 1, 0, 0, 4, 2, 3, 4, 0, 1,
       1, 4, 1, 0, 0, 0, 3, 2, 3, 1, 2, 1, 4, 0, 3, 1, 4, 3, 1, 0, 3, 0,
       2, 1, 4, 1, 1, 4, 2])

In [ ]:
accuracy_score(y_pred,y_test)
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.94      1.00      0.97        17
           1       0.71      0.62      0.67        16
           2       0.81      0.81      0.81        16
           3       0.91      0.91      0.91        11
           4       0.64      0.69      0.67        13

    accuracy                           0.81        73
   macro avg       0.80      0.81      0.81        73
weighted avg       0.81      0.81      0.81        73



In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV

In [ ]:
#n_neighbors = np.array(range(1,40))
#param_grid = dict(n_neighbors=n_neighbors)

In [ ]:
knn=KNeighborsClassifier(n_neighbors=1)
knn.fit(x_train1,y_train)
##grid = GridSearchCV(estimator=knn, param_grid=param_grid)
grid.fit(x_train1,y_train)



KNeighborsClassifier(n_neighbors=1)

In [ ]:
#print(grid.best_score_)
#print(grid.best_params_)


0.7118572292800968
{'n_neighbors': 1}


In [ ]:
y_pred_knn=knn.predict(x_test1)
y_pred_knn

array([2, 0, 0, 4, 0, 2, 1, 4, 2, 2, 3, 1, 3, 0, 2, 2, 3, 2, 1, 1, 0, 2,
       4, 3, 2, 2, 2, 2, 2, 4, 2, 1, 0, 4, 0, 1, 0, 0, 4, 2, 3, 4, 0, 3,
       1, 4, 1, 0, 0, 0, 3, 2, 3, 1, 3, 1, 1, 1, 3, 1, 1, 2, 1, 0, 3, 0,
       2, 3, 4, 1, 1, 4, 2])

In [ ]:
accuracy_score(y_pred_knn,y_test)
print(classification_report(y_pred_knn,y_test))

              precision    recall  f1-score   support

           0       0.78      0.93      0.85        15
           1       0.79      0.65      0.71        17
           2       0.81      0.68      0.74        19
           3       0.82      0.75      0.78        12
           4       0.57      0.80      0.67        10

    accuracy                           0.75        73
   macro avg       0.75      0.76      0.75        73
weighted avg       0.77      0.75      0.75        73



In [ ]:
from sklearn.svm import SVC
svc = SVC(kernel='linear',gamma='auto')
svc.fit(x_train1, y_train)

SVC(gamma='auto', kernel='linear')

In [ ]:
y_pred_svm=svc.predict(x_test1)
y_pred_svm

array([2, 0, 0, 4, 0, 0, 1, 4, 2, 1, 3, 2, 3, 0, 2, 2, 3, 2, 1, 1, 0, 2,
       0, 3, 2, 2, 2, 2, 2, 4, 2, 1, 0, 4, 0, 1, 0, 0, 4, 2, 3, 4, 0, 2,
       1, 4, 1, 0, 0, 0, 3, 2, 3, 1, 3, 2, 1, 0, 3, 1, 4, 3, 4, 0, 3, 0,
       2, 2, 4, 1, 1, 4, 2])

In [ ]:
accuracy_score(y_pred_svm,y_test)
print(classification_report(y_pred_svm,y_test))

              precision    recall  f1-score   support

           0       0.89      0.89      0.89        18
           1       0.79      0.85      0.81        13
           2       0.75      0.60      0.67        20
           3       0.91      0.91      0.91        11
           4       0.64      0.82      0.72        11

    accuracy                           0.79        73
   macro avg       0.80      0.81      0.80        73
weighted avg       0.80      0.79      0.79        73

